import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/components/custom/Header";
import { Footer } from "@/components/custom/Footer";
import { getDictionary } from "@/lib/dictionary";
import { Locale } from "@/i18n.config";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: any;
}) {
    const { lang }: { lang: Locale } = params;
    const { header, footer } = await getDictionary(lang);

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Header translation={header} />
                <main>
                    {children}
                </main>
                <Footer translation={footer} />
            </body>
        </html>
    );
}
